### PR TITLE
GitHub Enterprise Integration

### PR DESCRIPTION
**Pull request by error418**
Let me know what you think of the changes :)

I've also removed the blockquotes from the section `Commit Message Format` of the readme. GitHub seems to have problems rendering code blocks inside blockquotes

### CODE REVIEW

**Comment by error418** [comment]
Due to the withdrawal of oraclejdk7 in Ubuntu "trusty", no Oracle JDK 7 builds can be performed with Travis anymore. See https://github.com/travis-ci/travis-ci/issues/7884 for more details.

The travis configuration now utilizes `oraclejdk8` for builds

**Comment by tschulte** [comment]
Thank you for your pull request. I will have a look at it tomorrow.

**Comment by tschulte** [comment]
Thank you for your pull request. The new version should be available soon.

**Comment by tschulte** [comment]
v1.3.0 is now available.

**Pull request merged**
